[package]
name = "gen-ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bincode = "1.3.3"
parking_lot = "0.12.1"
serde = "1.0.164"
serde_json = "1.0.96"
